#!/usr/bin/env python
# animal.py - create animal table and
# retrieve information from it

import sys
import MySQLdb

try:
  conn = MySQLdb.connect (host="localhost",
			  user="michael",
			  passwd = "grapefruit",
			  db = "testrun")
except MySQLdb.Error, e:
  print "Error %d: %s" % (e.args[0], e.args[1])
  sys.exit (1)

cursor = conn.cursor ()
cursor.execute ("DROP TABLE IF EXISTS animal")
cursor.execute ("""
	CREATE TABLE animal
	(
	name	 CHAR(40),
	category CHAR(40)
	)
    """)
cursor.execute ("""
	INSERT INTO animal (name, category)
	VALUES
	 ('snake', 'reptile'),
	 ('frog', 'amphibian'),
	 ('tuna', 'fish'),
	 ('racoon', 'mammal');
     """)  
print "Number of rows inserted: %d" % cursor.rowcount

conn.commit();
conn.close();
